wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1656695702
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 8
      - 16
      4: 3.9.7
      5: 0.12.20
      8:
      - 1
      - 3
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 28
dropout1:
  desc: null
  value: 0.5
dropout2:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 30
filters1:
  desc: null
  value: 64
filters2:
  desc: null
  value: 64
kernel_size1:
  desc: null
  value: 5
kernel_size2:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.001
loss_function:
  desc: null
  value: sparse_categorical_crossentropy
